version: '3.8'
# Logging config
x-logging:
  &logging
  driver: "local"
  options:
    max-size: "200k"
    max-file: "10"

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    logging: *logging
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # TODO: figure out how to create and migrate db on first boot of container
    # TODO: figure out how to configure logging
    volumes:
      - .:/Rails-Docker
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    logging: *logging

volumes:
  postgres: